name: Build APP
on:
  workflow_dispatch:

  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'zulu'
          cache: 'gradle'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3
        with:
          cmdline-tools-version: 'latest'
          log-accepted-android-sdk-licenses: 'false'
          packages: 'tools platform-tools cmake;3.31.5 platforms;android-35 ndk;28.0.13004108'

      - name: Build APK
        run: ./gradlew :app:assembleRelease

      - name: display dir tree
        run: |
          set -o pipefail
          set -ex
          sudo tree --filelimit 20 || true

      - uses: actions/upload-artifact@v4
        name: Upload APK
        with:
          name: App bundle
          path: app/build/outputs/apk/release/app-release.apk
